# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-22 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FotosPortada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('foto', models.FileField(upload_to='fotoportada/')),
            ],
            options={
                'verbose_name_plural': 'Fotos de la portada',
            },
        ),
        migrations.CreateModel(
            name='LinkVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('link_video', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'videos tutoriales',
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Nombre del sitio', max_length=255)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('acerca', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Configuraci\xf3n del sitio',
            },
        ),
        migrations.AddField(
            model_name='linkvideos',
            name='sitio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.SiteConfiguration'),
        ),
        migrations.AddField(
            model_name='fotosportada',
            name='sitio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.SiteConfiguration'),
        ),
    ]
