# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 14:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntercambioTecnologia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Intercambio de Tecnolog\xeda',
            },
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Organizacion', 'Organizaci\xf3n'), ('Especialista', 'Especialista')], max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('logo', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='logos/')),
                ('objetivo', models.TextField()),
                ('contacto_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Persona de Contacto 1')),
                ('correo_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Correo 1')),
                ('telefono_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tel\xe9fono 1')),
                ('contacto_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Persona de Contacto 2')),
                ('correo_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Correo 2')),
                ('telefono_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tel\xe9fono 2')),
                ('ciudad', models.CharField(blank=True, help_text='Cuidad donde esta ubicada', max_length=255, null=True)),
                ('location', location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True, verbose_name='Ubicaci\xf3n')),
                ('tipo_organizacion', models.CharField(choices=[('Sector publico', 'Sector p\xfablico'), ('Sector privado', 'Sector privado'), ('Academia', 'Academia'), ('Asociacion', 'Asociaci\xf3n'), ('Cooperativa', 'Cooperativa'), ('Fundacion', 'Fundaci\xf3n'), ('ONG', 'ONG'), ('ONGI', 'ONGI'), ('Plataforma', 'Plataforma')], max_length=20, verbose_name='Tipo de Organizaci\xf3n')),
                ('ambito_accion', models.CharField(choices=[('Internacional', 'Internacional'), ('Regional', 'Regional'), ('Nacional', 'Nacional'), ('Local', 'Local')], max_length=20, verbose_name='\xc1mbito de Acci\xf3n')),
                ('cobertura', models.CharField(max_length=255, verbose_name='Cobertura Geogr\xe1fica')),
                ('periodo_permanencia', models.CharField(choices=[('2 a\xf1os', '2 a\xf1os'), ('3 a\xf1os', '3 a\xf1os'), ('4 a\xf1os', '4 a\xf1os'), ('5 a\xf1os', '5 a\xf1os'), ('M\xe1s de 5 a\xf1os', 'M\xe1s de 5 a\xf1os')], max_length=20, verbose_name='Per\xedodo de Permanencia')),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('miembros', models.IntegerField(blank=True, null=True, verbose_name='N\xb0 de Miembros/Socio')),
                ('tamano', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tama\xf1o')),
                ('actualizado', models.DateField(auto_now=True)),
                ('slug', models.SlugField(editable=False, max_length=450)),
                ('intercambio', models.ManyToManyField(to='directorio.IntercambioTecnologia', verbose_name='Intercambio de Tecnolog\xeda')),
            ],
            options={
                'verbose_name': 'Organizaci\xf3n/Especialista',
                'verbose_name_plural': 'Organizaciones/Especialistas',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Pa\xeds',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Participaci\xf3n en la cadena de valor',
            },
        ),
        migrations.CreateModel(
            name='ProductosServicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('foto', sorl.thumbnail.fields.ImageField(upload_to='productos-servicios/')),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directorio.Organizacion')),
            ],
            options={
                'verbose_name': 'Producto/Servicio',
                'verbose_name_plural': 'Productos y Servicios',
            },
        ),
        migrations.CreateModel(
            name='ServiciosCadena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Servicios en la Cadena de Valor',
            },
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo de actividad',
                'verbose_name_plural': 'Tipos de actividades',
            },
        ),
        migrations.AddField(
            model_name='organizacion',
            name='pais_sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directorio.Pais', verbose_name='Pa\xeds Sede'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='paises_labora',
            field=models.ManyToManyField(related_name='Paises', to='directorio.Pais', verbose_name='Pa\xedses donde Labora'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='participacion_cadena',
            field=models.ManyToManyField(to='directorio.Participacion', verbose_name='Participaci\xf3n en la Cadena de Valor'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='servicios',
            field=models.ManyToManyField(to='directorio.ServiciosCadena', verbose_name='Servicios  en la Cadena de Valor'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='tipo_actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directorio.TipoActividad', verbose_name='Tipo de Actividad'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
