# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 15:06
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='objetivo',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
