# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosServicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('foto', sorl.thumbnail.fields.ImageField(upload_to='productos-servicios/')),
            ],
            options={
                'verbose_name': 'Producto \xf3 Servicio',
                'verbose_name_plural': 'Productos y Servicios',
            },
        ),
        migrations.RemoveField(
            model_name='organizacion',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='organizacion',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='organizacion',
            name='telefono',
        ),
        migrations.AddField(
            model_name='organizacion',
            name='contacto_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Persona de Contacto 1'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='contacto_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Persona de Contacto 2'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='correo_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Correo 1'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='correo_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Correo 2'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='telefono_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tel\xe9fono 1'),
        ),
        migrations.AddField(
            model_name='organizacion',
            name='telefono_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tel\xe9fono 2'),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Cuidad donde esta ubicada', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='tamano',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tama\xf1o'),
        ),
        migrations.AddField(
            model_name='productosservicios',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directorio.Organizacion'),
        ),
    ]
