# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0002_auto_20171012_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productosservicios',
            options={'verbose_name': 'Producto/Servicio', 'verbose_name_plural': 'Productos y Servicios'},
        ),
    ]
