# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0002_auto_20171120_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizacion',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='periodo_permanencia',
            field=models.CharField(choices=[('2 a\xf1os', '2 a\xf1os'), ('3 a\xf1os', '3 a\xf1os'), ('4 a\xf1os', '4 a\xf1os'), ('5 a\xf1os', '5 a\xf1os'), ('Mas de 5 a\xf1os', 'M\xe1s de 5 a\xf1os')], max_length=20, verbose_name='Per\xedodo de Permanencia'),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='tipo_organizacion',
            field=models.CharField(choices=[('Sector publico', 'Sector p\xfablico'), ('Sector privado', 'Sector privado'), ('Academia', 'Academia'), ('Asociacion', 'Asociaci\xf3n'), ('Cooperativa', 'Cooperativa'), ('Fundacion', 'Fundaci\xf3n'), ('ONG', 'ONG'), ('ONGI', 'ONGI'), ('Plataforma', 'Plataforma'), ('Consultor', 'Consultor')], max_length=20, verbose_name='Tipo de Organizaci\xf3n'),
        ),
    ]
