# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-27 19:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directorio', '0005_auto_20171205_0814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redes',
            options={'verbose_name': 'Red', 'verbose_name_plural': 'Redes'},
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='servicios',
            field=models.ManyToManyField(to='directorio.ServiciosCadena', verbose_name='Servicios que brinda la Organizaci\xf3n'),
        ),
        migrations.RemoveField(
            model_name='organizacion',
            name='usuario',
        ),
        migrations.AddField(
            model_name='organizacion',
            name='usuario',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='redes',
            name='opcion',
            field=models.CharField(choices=[('Sitio web', 'Sitio web'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Youtube', 'Youtube'), ('Google+', 'Google+'), ('Instagram', 'Instagram'), ('Linkedin', 'Linkedin'), ('Flickr', 'Flickr'), ('Pinterest', 'Pinterest'), ('Vimeo', 'Vimeo'), ('Otra', 'Otra')], max_length=25),
        ),
    ]
