# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 15:34
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0005_organizacion_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='logo',
            field=sorl.thumbnail.fields.ImageField(default=1, upload_to='logos/'),
            preserve_default=False,
        ),
    ]
