# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 20:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0006_organizacion_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacion',
            name='tipo',
            field=models.CharField(choices=[('Organizaci\xf3n', 'Organizaci\xf3n'), ('Especialista', 'Especialista')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='logo',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='tipo_organizacion',
            field=models.CharField(choices=[('Sector publico', 'Sector p\xfablico'), ('Sector privado', 'Sector privado'), ('Academia', 'Academia'), ('Asociacion', 'Asociaci\xf3n'), ('Cooperativa', 'Cooperativa'), ('Fundacion', 'Fundaci\xf3n'), ('ONG', 'ONG'), ('ONGI', 'ONGI'), ('Plataforma', 'Plataforma')], max_length=20, verbose_name='Tipo de Organizaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
