# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-12 16:19
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0006_auto_20180227_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizacion',
            name='intercambio',
        ),
        migrations.RemoveField(
            model_name='organizacion',
            name='periodo_permanencia',
        ),
        migrations.RemoveField(
            model_name='organizacion',
            name='tamano',
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='objetivo',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Descripci\xf3n de la Organizaci\xf3n'),
        ),
    ]
