# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-26 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0007_auto_20180412_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, null=True)),
                ('url', models.URLField()),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directorio.Organizacion')),
            ],
            options={
                'verbose_name': 'Link de Videos',
                'verbose_name_plural': 'Link de Videos',
            },
        ),
    ]
