# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-22 03:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0008_linkvideos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizacion',
            options={'ordering': ['-id'], 'verbose_name': 'Organizaci\xf3n/Especialista', 'verbose_name_plural': 'Organizaciones/Especialistas'},
        ),
    ]
