# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-18 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0009_auto_20190521_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='productosservicios',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripci\xf3n'),
        ),
    ]
