# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-29 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0011_remove_organizacion_cobertura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='tipo_organizacion',
            field=models.CharField(choices=[('Sector publico', 'Gobierno'), ('Sector privado', 'Empresa'), ('Academia', 'Academia'), ('Asociacion', 'Asociaci\xf3n'), ('Cooperativa', 'Cooperativa'), ('Fundacion', 'Fundaci\xf3n'), ('ONG', 'ONG'), ('ONGI', 'ONGI'), ('Plataforma', 'Plataforma'), ('Consultor', 'Consultor'), ('Financiera', 'Financiera'), ('Banco', 'Banco'), ('Centro Investigacion', 'Centro de investigaci\xf3n')], max_length=20, verbose_name='Tipo de Organizaci\xf3n'),
        ),
    ]
