# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-29 04:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0012_auto_20190628_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizacion',
            name='tipo_actividad',
        ),
    ]
