# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-10-01 04:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0013_remove_organizacion_tipo_actividad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ('nombre',), 'verbose_name': 'Pa\xeds', 'verbose_name_plural': 'Paises'},
        ),
    ]
