# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-10-01 04:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directorio', '0014_auto_20200930_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_organizacion', models.CharField(blank=True, choices=[('Sector publico', 'Gobierno'), ('Sector privado', 'Empresa'), ('Academia', 'Academia'), ('Asociacion', 'Asociaci\xf3n'), ('Cooperativa', 'Cooperativa'), ('Fundacion', 'Fundaci\xf3n'), ('ONG', 'ONG'), ('ONGI', 'ONGI'), ('Plataforma', 'Plataforma'), ('Consultor', 'Consultor'), ('Financiera', 'Financiera'), ('Banco', 'Banco'), ('Centro Investigacion', 'Centro de investigaci\xf3n')], max_length=20, null=True)),
                ('asunto', models.CharField(max_length=300)),
                ('contenido', models.TextField()),
                ('destinatario', models.ManyToManyField(blank=True, to='directorio.Organizacion')),
                ('pais', models.ManyToManyField(blank=True, to='directorio.Pais')),
                ('participacion_cadena', models.ManyToManyField(blank=True, to='directorio.Participacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
            },
        ),
    ]
